const TRIGGER_TYPES = {
  TRANSACTION_AMOUNT: 'txAmount',
  TRANSACTION_VOLUME: 'txVolume',
  TRANSACTION_VELOCITY: 'txVelocity',
  CONSECUTIVE_DAYS: 'consecutiveDays'
}

const DIRECTIONS = {
  CASH_IN: 'cashIn',
  CASH_OUT: 'cashOut',
  BOTH: 'both'
}

const REQUIREMENTS = {
  PHONE_NUMBER: 'sms',
  ID_CARD_DATA: 'idCardData',
  SANCTIONS: 'sanctions',
  ID_CARD_PHOTO: 'idCardPhoto',
  FACEPHOTO: 'facephoto',
  SUSPEND: 'suspend',
  BLOCK: 'block'
}

const ORDERED_REQUIREMENTS = [
  REQUIREMENTS.PHONE_NUMBER,
  REQUIREMENTS.ID_CARD_PHOTO,
  REQUIREMENTS.ID_CARD_DATA,
  REQUIREMENTS.SANCTIONS,
  REQUIREMENTS.FACEPHOTO,
  REQUIREMENTS.SUSPEND,
  REQUIREMENTS.BLOCK,
]

module.exports = {
  TRIGGER_TYPES,
  DIRECTIONS,
  REQUIREMENTS,
  ORDERED_REQUIREMENTS
}
