
module.exports = {
  '0': 'Function Success',
  '-1': 'Hardware Error or Function Fail',
  '-2': 'Function of the previous operation is not completed',
  '-3': 'Invalid Parameter or Invalid Data',
  '-4': 'Secure Mode Error (EPP Device Only)',
  '-5': 'Key canceled at the input (EPP Device Only)',
  '-6': 'Device is not ready',
  '-7': 'Device is already open',
  '-8': 'SDK or device internal error',
  '-9': 'Timeout',
  '-10': 'Receive data buffer overflow',
  '-11': 'Communication port open error',
  '-12': 'Image Error (RPU Device Only)',
  '-13': 'Return the accepted bill (BAU, BA2 Device Only)',
  '-14': 'Not present bill in the escrow (BAU, BA2 Device Only)',
  '-15': 'Present bill in the escrow (BAU, BA2 Device Only)',
  '-16': 'Return if the password is default when call secure mode command (EPP Device Only)',
  '-17': 'Returns if the serial port is already open when opening the device.',
  '-18': 'License key authentication failed (CDU Device Only)',
  '-19': 'Failed to send USB data (CIS, CSK Device Only)',
  '-20': 'The image size is different from (width x hight) values. (CIS, CSK Device Only)',
  '-21': 'Returned when calling an not supported method',
  '-22': 'Image processing error (RPU Device Only)',
  '-23': 'Data length is too long',
  '-24': 'Image size cannot be processed (RPU Device Only)',
  '-25': 'The file not exist or not opened in the file path',
  '-26': 'Unknown error occurs',
  '-27': 'Need to check the status of the device to determine whether to proceed.',
  '3': 'Waiting or doing some action (BAU, BA2 Device Only)'
}
