#!/bin/bash
sleep 10

#! start chromium on the background
/usr/bin/chromium-browser --touch-events=enabled --disable-pinch --incognito --kiosk file:///opt/apps/machine/lamassu-machine/ui/start.html &

#! wait until chromium is opened
until wmctrl -l | grep -m 1 "Chromium"
do 
	sleep 1
done

#! activate chromium window and press F11 on it
xdotool search --sync --onlyvisible --class "Chromium" windowactivate key F11

#! wait for chromium to close
wait