#!/bin/bash

while true ; do
    # Allow system some time to establish connection
    sleep 180

    if wpa_cli -i wlan0 signal_poll | grep -q FAIL ; then
        echo "Network connection is down, resetting interface."
        ifdown --force wlan0
        sleep 5
        ifup wlan0
    fi
done