exports.BALANCE_LOW = 'balanceLow'
exports.IDLE = 'idle'
exports.NETWORK_DOWN = 'networkDown'
exports.PENDING_IDLE = 'pendingIdle'
exports.POLL_UPDATE = 'pollUpdate'
exports.START = 'start'
exports.UNPAIRED = 'unpaired'
