#!/bin/bash

# This creates a zipped version of update.tar for v64 aaeons. It can be discarded once all machines are upgraded.
set -e

PACKAGE_NAME=$1

if [ -z "$LAMASSU_EXPORT" -o -z "$PACKAGE_NAME" ]
  then
    echo "quiet_zip <package name>"
    echo "LAMASSU_EXPORT environment variable must be set."
    exit 1
fi

SOURCE_DIR=$LAMASSU_EXPORT/$PACKAGE_NAME
SOURCE_DIR=$(unset CDPATH && cd "$SOURCE_DIR" && pwd)

TARGET_DIR=$SOURCE_DIR-aaeon

mkdir -p $TARGET_DIR
cp $SOURCE_DIR/update.tar $TARGET_DIR
cp $SOURCE_DIR/info.json $TARGET_DIR

gzip -q $TARGET_DIR/update.tar
mv $TARGET_DIR/update.tar.gz $TARGET_DIR/update.tar

echo "Success."