#!/bin/bash

SCRIPT_DIR=$(dirname $0)

supervisorctl stop
rm -rf /etc/supervisor
cp -r $SCRIPT_DIR/../hardware/system/ssuboard/supervisor /etc/supervisor

# Supervisor can have a race condition
# The sleep is for mitigation
sleep 30s
supervisorctl start

echo 'Supervisor configuration updated'