FROM lamassu/upboard-build:2.0 as build
  ARG VERSION
  ARG PASSWORD

  RUN mkdir lamassu-machine && cd lamassu-machine && \
    curl -sL https://ssubucket.ams3.digitaloceanspaces.com/deploy-files_2019.06.07.txz | xz -dc | tar -x

  COPY ["package.json", "package-lock.json", "./lamassu-machine/"]
  RUN cd lamassu-machine && npm install
  COPY . ./lamassu-machine/

  RUN cd lamassu-machine && \
      bash ./deploy/codebase/ci-build.sh && \
      bash ./deploy/codebase/package.sh