#!/bin/bash

set -e

FONT_CSS=$1
FONT_DIR=$2
BASE_DIR=${3-.}
SCRIPT_DIR=$(dirname $0)

if [ -z "$FONT_CSS" -o -z "$FONT_DIR" -o -z "$BASE_DIR" ]; then
  echo "Usage: install <font css path> <font dir> <lamassu-machine dir>"
  echo "Example: install css/source-code-pro.css ~/Downloads/fonts/source-code-pro ~/projects/lamassu-machine"
  exit 1
fi

node $SCRIPT_DIR/fonts_css.js $FONT_FAMILY $BASE_DIR

if [ $? -ne 0 ]; then
  exit 2
fi

TARGET_FONTS_DIR=$BASE_DIR/ui/css/fonts
mkdir -p $TARGET_FONTS_DIR
cp $FONT_DIR/* $TARGET_FONTS_DIR

echo "Fonts successfully copied."
